import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const moon = '~sampel-siglup-narwet';
test.beforeEach(async ({request,page})=>{await request.get('http://127.0.0.1:8085/reset');page.on('pageerror',e=>console.log('PAGE ERROR',e.message));});
test('fleet lists moons oldest first; boot shows progress; snapshots return to a point',async({page})=>{
  await page.goto('/'); await expect(page.getByRole('button',{name:moon,exact:true})).toBeVisible();
  // ~dozlet was booted first, though the host lists ~sampel first
  await expect(page.locator('tbody tr .ship-link strong')).toHaveText(['~dozlet-siglup-narwet',moon]);
  await page.screenshot({path:'test-results/fleet-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Boot moon',exact:true}).click();
  const name=await page.getByLabel('Moon name',{exact:true}).inputValue();
  await page.getByRole('dialog').getByRole('button',{name:'Boot moon',exact:true}).click();
  const status=page.getByRole('status',{name:'Boot status'});
  await expect(status).toContainText(`Booting ${name}`);
  await expect(page.locator('.booting-row')).toContainText(name);
  await page.screenshot({path:'test-results/boot-status.png',fullPage:true});
  await expect(status).toContainText(`${name} is ready`,{timeout:10000});
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','100');
  await expect(page.locator('tbody tr .ship-link strong').last()).toHaveText(name);
  // the moon's snapshot tool lists its snapshots and takes new ones
  await page.getByRole('button',{name:`Snapshots of ${moon}`,exact:true}).click();
  const dialog=page.getByRole('dialog');
  await expect(dialog.getByRole('heading',{name:`Snapshots of ${moon}`})).toBeVisible();
  await expect(dialog.locator('.snap-list')).toContainText('baseline');
  await dialog.getByLabel('Snapshot name').fill('test-checkpoint');
  await expect(dialog.getByLabel(`Keep ${moon} running after saving`)).toBeChecked();
  await dialog.getByRole('button',{name:'Take snapshot'}).click();
  await expect(dialog.locator('.snap-list li').first()).toContainText('test-checkpoint');
  await page.screenshot({path:'test-results/moon-snapshots.png',fullPage:true});
  await dialog.getByRole('button',{name:'Close',exact:true}).click();
  await expect(page.getByRole('button',{name:`Pause ${moon}`,exact:true})).toBeVisible();
  // without "keep running" the moon stays paused, as before
  await page.getByRole('button',{name:`Snapshots of ${moon}`,exact:true}).click();
  await dialog.getByLabel('Snapshot name').fill('paused-checkpoint');
  await dialog.getByLabel(`Keep ${moon} running after saving`).uncheck();
  await dialog.getByRole('button',{name:'Take snapshot'}).click();
  await expect(dialog.locator('.snap-list')).toContainText('paused-checkpoint');
  // restore straight from the moon's tool
  await dialog.locator('.snap-list li').filter({hasText:'test-checkpoint'}).getByRole('button',{name:'Restore',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText(moon);
  await expect(page.getByRole('dialog')).toContainText('new network era');
  await page.getByRole('button',{name:'Restore & resume'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button',{name:`Pause ${moon}`,exact:true})).toBeVisible();
  await page.getByRole('button',{name:/^Snapshots \d/}).click();
  await expect(page.locator('article').first()).toContainText('/paused-checkpoint');
  await page.getByRole('button',{name:/^Moons/}).click();
  await page.getByRole('button',{name:`Remove ${name}`,exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Remove moon',exact:true}).click();
  await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
});
test('boot picker lists every desk and adds Landscape for docket apps',async({page})=>{
  await page.goto('/'); await page.getByRole('button',{name:'Boot moon',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await expect(dialog.getByLabel('Include %base')).toBeChecked();
  await expect(dialog.getByLabel('Include %base')).toBeDisabled();
  await expect(dialog.getByLabel('Include %noltbook-data')).toBeVisible();
  await dialog.getByLabel('Include %glurff').check();
  await expect(dialog.getByLabel('Include %landscape')).toBeChecked();
  await expect(dialog.getByLabel('Include %landscape')).toBeDisabled();
  await expect(dialog).toContainText('Added %landscape because %glurff has a Landscape tile.');
  // only desks the host syncs from someone else offer that ship as a source
  await expect(dialog.getByLabel('Updates for %base')).toHaveCount(0);
  await expect(dialog.getByLabel('Updates for %landscape')).toHaveCount(0);
  await expect(dialog.getByLabel('Updates for %glurff')).toHaveValue('host');
  await dialog.getByLabel('Updates for %glurff').selectOption('publisher');
  await page.screenshot({path:'test-results/picker-desktop.png',fullPage:true});
  const name=await dialog.getByLabel('Moon name',{exact:true}).inputValue();
  await dialog.getByRole('button',{name:'Boot moon',exact:true}).click();
  const row=page.locator('tbody tr').filter({hasText:name});
  await expect(row).toContainText('%base'); await expect(row).toContainText('%glurff'); await expect(row).toContainText('%landscape');
  await expect(row.locator('.desk-state',{hasText:'%glurff'}).first()).toHaveAttribute('title',/updates from ~nolset\/%glurff/);
  await expect(row.locator('.desk-state',{hasText:'%landscape'}).first()).toHaveAttribute('title',/updates from ~siglup-narwet\/%landscape/);
});
test('the Dojo is a terminal: typing goes straight to the moon',async({page,request})=>{
  await page.goto('/');await page.getByRole('button',{name:`Open Dojo for ${moon}`}).click();
  const rows=page.locator('.xterm-rows');
  await expect(rows).toContainText('sampel-siglup-narwet:dojo>');
  await expect(page.getByLabel(`Command for ${moon}`)).toHaveCount(0);
  await page.getByTestId('terminal').click();
  await page.keyboard.type('(add 2 2x');await page.keyboard.press('Backspace');await page.keyboard.type(')');
  await expect(rows).toContainText('dojo> (add 2 2)');
  await page.keyboard.press('Enter');
  await expect(rows).toContainText('4');
  await page.waitForTimeout(150); await page.screenshot({path:'test-results/dojo-desktop.png',fullPage:true});
  const log=await (await request.get('http://127.0.0.1:8085/term-log')).json();
  const acts=log.filter(e=>e.who===moon).map(e=>e.act);
  expect(acts.some(a=>a.size&&a.size.cols>20&&a.size.rows>5)).toBeTruthy();
  expect(acts.some(a=>'hail' in a)).toBeTruthy();
  const belts=acts.flatMap(a=>a.belts||[]);
  expect(belts.map(b=>b.txt).filter(Boolean).join('')).toBe('(add 2 2x)');
  expect(belts.some(b=>'bac' in b)).toBeTruthy(); expect(belts.some(b=>'ret' in b)).toBeTruthy();
  await expect(page.getByRole('button',{name:'Download transcript'})).toBeVisible();
});
test('mobile layout and keyboard dialog cancellation',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByRole('button',{name:moon,exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:'test-results/fleet-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Boot moon',exact:true}).click();await expect(page.getByLabel('Include %noltbook-data')).toBeVisible();await page.screenshot({path:'test-results/picker-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:moon,exact:true}).click();await page.screenshot({path:'test-results/dojo-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('offline is explicit and disables actions',async({page})=>{
  await page.route('**/~/scry/theseus/ui.json',route=>route.fulfill({status:503,body:'offline'}));await page.goto('/');
  await expect(page.getByRole('alert')).toContainText('503');await expect(page.getByRole('button',{name:'Boot moon',exact:true})).toBeDisabled();
});
test('workspace is top-aligned and closing the page deletes the channel',async({page,request})=>{
  await page.setViewportSize({width:1280,height:1600});await page.goto('/');await expect(page.getByRole('button',{name:moon,exact:true})).toBeVisible();
  expect(await page.locator('main').evaluate(el=>el.getBoundingClientRect().top)).toBeLessThan(5);
  await page.getByRole('button',{name:`Open Dojo for ${moon}`}).click();await expect(page.locator('.xterm-rows')).toContainText('dojo>');
  await page.goto('about:blank');
  await expect.poll(async()=>Number(await (await request.get('http://127.0.0.1:8085/deletes')).text())).toBeGreaterThan(0);
});
test('Landscape opens on the moon origin and logs in with a posted code',async({page,context,request})=>{
  await page.goto('/');await expect(page.getByRole('button',{name:moon,exact:true})).toBeVisible();
  const login=context.waitForEvent('request',r=>r.method()==='POST'&&r.url().endsWith('/~/login'));
  await page.getByRole('button',{name:`Open Landscape for ${moon}`}).click();
  const req=await login;
  expect(req.url()).toBe('http://sampel-siglup-narwet.localhost:5174/~/login');
  expect(req.postData()).toBe('password=lidlut-tabwed-pillex-ridrup&redirect=%2Fapps%2Flandscape%2F');
});
test('a moon without Landscape offers to install it, then opens',async({page,context})=>{
  await page.goto('/');await page.getByRole('button',{name:'Boot moon',exact:true}).click();
  const name=await page.getByLabel('Moon name',{exact:true}).inputValue();
  await page.getByRole('dialog').getByRole('button',{name:'Boot moon',exact:true}).click();
  await expect(page.getByRole('button',{name,exact:true})).toBeVisible();
  await page.getByRole('button',{name:`Open Landscape for ${name}`}).click();
  await expect(page.getByRole('dialog')).toContainText('does not have Landscape');
  await expect(page.getByRole('dialog')).toContainText('|install ~siglup-narwet %landscape');
  await page.getByRole('button',{name:'Install Landscape'}).last().click();
  await expect(page.getByTestId('terminal')).toBeVisible();
  const login=context.waitForEvent('request',r=>r.method()==='POST'&&r.url().endsWith('/~/login'));
  await page.getByRole('button',{name:'Landscape',exact:true}).click();
  expect((await login).url()).toBe(`http://${name.slice(1)}.localhost:5174/~/login`);
});
test('+code is shown on request and copied',async({page,context})=>{
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  await page.goto('/');await page.getByRole('button',{name:`Show +code for ${moon}`}).click();
  await expect(page.getByTestId('moon-code')).toHaveText('lidlut-tabwed-pillex-ridrup');
  await page.getByRole('button',{name:'Copy code'}).click();
  await expect(page.getByRole('status').filter({hasText:'Copied'})).toBeVisible();
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('lidlut-tabwed-pillex-ridrup');
  await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('without a gateway, Landscape explains instead of opening a blank tab',async({page,context,request})=>{
  await request.get('http://127.0.0.1:8085/gateway-down');
  await page.goto('/');await expect(page.getByRole('button',{name:/^Gateway/})).toContainText('off');
  await page.getByRole('button',{name:`Open Landscape for ${moon}`}).click();
  await expect(page.getByRole('dialog')).toContainText('No web gateway is running');
  expect(context.pages()).toHaveLength(1);
  await page.getByRole('button',{name:'Open Gateway settings'}).click();
  await expect(page.getByRole('heading',{name:'Gateway'})).toBeVisible();
  await expect(page.locator('.gateway-status')).toContainText('Not running');
  await expect(page.locator('.gateway-status')).toContainText('ops/theseus-gateway install');
});
test('gateway settings validate, apply, and drive moon origins',async({page,context})=>{
  await page.goto('/');await page.getByRole('button',{name:/^Gateway/}).click();
  const status=page.locator('.gateway-status'), form=page.locator('.gateway-form');
  await expect(status).toContainText('Running');await expect(status).toContainText('http://{moon}.localhost:5174');
  await expect(status).toContainText('Can reach the gateway');
  await page.screenshot({path:'test-results/gateway-desktop.png',fullPage:true});
  await page.getByRole('radio',{name:/Declared port/}).check();
  await page.getByLabel('Gateway port').fill('70000');await page.getByRole('button',{name:'Save settings'}).click();
  await expect(form.getByRole('alert')).toContainText('1 to 65535');
  await page.getByLabel('Gateway port').fill('9000');await page.getByRole('button',{name:'Save settings'}).click();
  await expect(status).toContainText('Applying change');await expect(status).toContainText('http://{moon}.localhost:9000');
  await page.getByRole('radio',{name:/Hosting/}).check();
  await page.getByLabel('Moon address').fill('https://example.com/{moon}');await page.getByRole('button',{name:'Save settings'}).click();
  await expect(form.getByRole('alert')).toContainText('{moon} in the hostname');
  await page.getByLabel('Moon address').fill('http://{moon}.localhost:5174');await page.getByRole('button',{name:'Save settings'}).click();
  await expect(status).toContainText('Hosting');
  await page.getByRole('button',{name:/^Moons/}).click();
  const login=context.waitForEvent('request',r=>r.method()==='POST'&&r.url().endsWith('/~/login'));
  await page.getByRole('button',{name:`Open Landscape for ${moon}`}).click();
  expect((await login).url()).toBe('http://sampel-siglup-narwet.localhost:5174/~/login');
});
test('gateway view fits a phone',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  await page.getByRole('button',{name:/^Gateway/}).click();await expect(page.locator('.gateway-status')).toContainText('Running');
  await page.screenshot({path:'test-results/gateway-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('sidecar view downloads a fleet map and builds the run command',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:/^Sidecar/}).click();
  await expect(page.getByRole('heading',{name:'Sidecar',exact:true})).toBeVisible();
  const bundle=page.getByRole('link',{name:'Download sidecar'});
  await expect(bundle).toHaveAttribute('href','/apps/theseus/sidecar.mjs');
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download moon list'}).click();
  const fleet=await download;
  expect(fleet.suggestedFilename()).toBe('theseus-moons.json');
  const map=JSON.parse(await readFile(await fleet.path(),'utf8'));
  expect(Object.keys(map)).toEqual([moon,'~dozlet-siglup-narwet']);
  expect(Object.values(map).every(value=>/^\d+$/.test(value))).toBeTruthy();
  await page.getByLabel('Host pier path').fill('/srv/pier');
  await page.getByLabel('Host Ames UDP port').fill('55056');
  await expect(page.locator('.sidecar-command')).toContainText("/srv/pier/.urb/dev/theseus-pyre/ames");
  await expect(page.locator('.sidecar-command')).toContainText('--gateway siglup-narwet=127.0.0.1:55056');
  await page.screenshot({path:'test-results/sidecar-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/sidecar-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
